# Generated by Django 5.1.1 on 2024-10-27 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_body_remove_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='thumbanils/'),
            preserve_default=False,
        ),
    ]
