# Generated by Django 5.1.1 on 2025-03-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project_description',
            field=models.TextField(null=True),
        ),
    ]
