# Generated by Django 5.1.1 on 2025-03-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='project_name',
            new_name='blog_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='project_description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='project_link',
        ),
    ]
