# Generated by Django 5.1.1 on 2025-03-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_project_name_post_blog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notion_link',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
